#logging:
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%thread] %-5level  %class{36}.%M %L  - %msg%n"
#
server:
  port: 8083

dragon:
  worker: vano
  voin: gogi


logging-service:
  enabled: on
  pointcuts:
    - pointcut: execution(* ru.clevertec..*controller*..*(..))
      enabled: on
      logging-format:
        date-format: HH:mm:ss.SSS
        print-arguments: true
