#logging:
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%thread] %-5level  %class{36}.%M %L  - %msg%n"
#
server:
  port: 8083

dragon:
  enabled: on
  worker: vano
  warriorKing: gogi
  warriors:
    - w1
    - w2

buhlo:
  - vodka
  - pivo
  - vino

loggingService:
  enabled: on
  pointcuts:
    - enabled: on
      patterns:
        - execution(* ru.clevertec..*controller*..*(..))
        - execution(* ru.clevertec..*service*..*(..))
      loggingFormat:
        dateFormat: HH:mm:ss.SSS
        printArguments: true
